flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.9.2
- hostname-1.0
- parallel-io-0.3.3
- regex-base-0.93.2
- regex-posix-0.95.2
- test-framework-0.8.1.1
- tf-random-0.5
- xml-1.3.14
resolver: lts-9.0
